# Generated by Django 6.0.5 on 2026-06-01 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('horario', models.CharField(blank=True, default='', max_length=120)),
                ('servicios', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tiene_cabanas', models.BooleanField(default=True)),
                ('capacidad_max_cabana', models.PositiveIntegerField(default=0)),
                ('precio_cabana', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_max_camping', models.PositiveIntegerField(default=0)),
                ('precio_camping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parques.parque')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parques.servicio')),
            ],
        ),
    ]
