# Generated by Django 5.2.14 on 2026-05-26 15:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=255)),
                ('servicios', models.JSONField(blank=True, default=list)),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('capacidad_max_camping', models.PositiveIntegerField(default=0)),
                ('capacidad_max_cabania', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cupo_camping', models.PositiveIntegerField()),
                ('cupo_cabania', models.PositiveIntegerField()),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='parques.parque')),
            ],
            options={
                'ordering': ['parque', 'fecha'],
                'unique_together': {('parque', 'fecha')},
            },
        ),
    ]
