# Generated by Django 6.0.5 on 2026-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parque',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
