# Generated by Django 6.0.5 on 2026-05-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parque',
            name='horario',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parque',
            name='servicios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parque',
            name='tiene_cabanas',
            field=models.BooleanField(default=True),
        ),
    ]
