# Generated by Django 6.0.5 on 2026-05-31 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0002_parque_direccion_parque_horario_parque_servicios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parque',
            name='capacidad_total',
        ),
        migrations.AddField(
            model_name='parque',
            name='capacidad_max_cabana',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parque',
            name='capacidad_max_camping',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ServiciosParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parques.parque')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parques.servicio')),
            ],
        ),
    ]
