# Generated by Django 6.0.5 on 2026-05-27 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('huespedes', models.PositiveIntegerField()),
                ('tipo_hospedaje', models.CharField(choices=[('cabana', 'Cabaña'), ('camping', 'Camping')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='parques.parque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('capacidad_disponible', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('pocos', 'Pocos lugares'), ('agotado', 'Agotado'), ('mantenimiento', 'Mantenimiento')], default='libre', max_length=20)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='parques.parque')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('parque', 'fecha')},
            },
        ),
    ]
