# Generated by Django 5.2.14 on 2026-05-26 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('num_asistentes', models.PositiveIntegerField()),
                ('tipo_visita', models.CharField(choices=[('CABAÑA', 'Cabaña'), ('CAMPING', 'Camping')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='parques.parque')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
