# Generated by Django 6.0.5 on 2026-06-01 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadparque',
            unique_together={('parque', 'fecha')},
        ),
    ]
