# Generated by Django 5.2.14 on 2026-05-26 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
